### ISSUE TITLE
Errors at script launch

### ISSUE THREAD

**Issue by v4nadium** [eraserhead1897/xf-tile#2]
All dependencies installed. Files moved at the right places.
On Linux Mint 19 XFCE fresh install.
```
$ python xf_tile.py
Traceback (most recent call last):
  File "xf-tile.py", line 218, in <module>
    window = {'ID': int(float(output[0][1:])), 'APP': output[1], 'WS': get_current_workspace()}
  File "xf-tile.py", line 102, in get_current_workspace
    workspaces = subprocess.check_output(['wmctrl', '-d'], text=True)
  File "/usr/lib/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.6/subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
TypeError: __init__() got an unexpected keyword argument 'text'
```

**Comment by jstet** [comment]
> All dependencies installed. Files moved at the right places.
> On Linux Mint 19 XFCE fresh install.
> 
> ```
> $ python xf_tile.py
> Traceback (most recent call last):
>   File "xf-tile.py", line 218, in <module>
>     window = {'ID': int(float(output[0][1:])), 'APP': output[1], 'WS': get_current_workspace()}
>   File "xf-tile.py", line 102, in get_current_workspace
>     workspaces = subprocess.check_output(['wmctrl', '-d'], text=True)
>   File "/usr/lib/python3.6/subprocess.py", line 356, in check_output
>     **kwargs).stdout
>   File "/usr/lib/python3.6/subprocess.py", line 423, in run
>     with Popen(*popenargs, **kwargs) as process:
> TypeError: __init__() got an unexpected keyword argument 'text'
> ```

I get the same errors
